apiVersion: apps/v1
kind: Deployment
metadata:  
  name: db-deployment
spec:
  replicas: 1  
  selector:
    matchLabels:      
      app: db
  template:    
    metadata:
      labels:        
        app: db
    spec:      
      containers:
        - name: mysql
          image: mysql:8.0          
          env:
            - name: MYSQL_ROOT_PASSWORD              
            value: "rootpassword"
            - name: MYSQL_DATABASE              
            value: "chatapp"
            - name: MYSQL_USER              
            value: "user"
            - name: MYSQL_PASSWORD
            value: "password"          
          sports:
            - containerPort: 3306