apiVersion: apps/v1
kind: Deployment
metadata:  
  name: web
  labels:    
    app: web
spec:  
  replicas: 1
  selector:
    matchLabels:      
      app: web
  template:    
    metadata:
      labels:        
        app: web
    spec:      
      containers:
      - name: web        
        image: mykolasc/chatapp:latest
        ports:        
        - containerPort: 8080
        env:        
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"        
        - name: ConnectionStrings__DefaultConnection
          value: "Server=localhost;Database=chat;User=root;Password=newpassword;"
